# Generated by Django 5.0.1 on 2024-02-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.AddField(
            model_name='student',
            name='annual_income',
            field=models.PositiveIntegerField(default=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='house_name',
            field=models.CharField(default='hai', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(default='mom', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='parent_occupation',
            field=models.CharField(default='business', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dist',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='place',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
