# Generated by Django 5.0.2 on 2024-02-07 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_alter_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_id',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='pgm_id',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='programme',
            name='pgm_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
