# Generated by Django 5.0.1 on 2024-02-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0002_room_allotment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.CharField(max_length=50),
        ),
    ]
