# Generated by Django 5.0.2 on 2024-02-07 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_department_dept_id_alter_department_dept_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotment',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hostel.student'),
        ),
    ]
