# Generated by Django 5.0.1 on 2024-03-02 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0003_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterUniqueTogether(
            name='messbill',
            unique_together={('month', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='studentbill',
            unique_together={('name', 'month', 'year')},
        ),
        migrations.CreateModel(
            name='ContinuousAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('streak', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hostel.student')),
            ],
            options={
                'unique_together': {('name', 'month', 'year')},
            },
        ),
    ]
