# Generated by Django 3.2.12 on 2024-02-07 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='stud_id',
            new_name='name',
        ),
    ]
