# Generated by Django 5.0.1 on 2024-02-17 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_studentbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='month',
            field=models.CharField(default='January 2024', max_length=20),
            preserve_default=False,
        ),
    ]
