# Generated by Django 5.0.1 on 2024-02-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_studentbill_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbill',
            name='year',
            field=models.SmallIntegerField(default=2024),
            preserve_default=False,
        ),
    ]
