# Generated by Django 5.0.1 on 2024-02-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0009_messbill_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='E_Grantz',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='No', max_length=10),
            preserve_default=False,
        ),
    ]
