# Generated by Django 5.0.1 on 2024-02-18 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0010_student_e_grantz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='category',
            field=models.CharField(choices=[('OBC', 'OBC'), ('OEC', 'OEC'), ('GENERAL', 'GENERAL'), ('SC', 'SC'), ('ST', 'ST')], max_length=20),
        ),
    ]
